language: php

php:
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=3.0.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - composer install -n --dev --prefer-source

script:
  - vendor/phpspec/phpspec/bin/phpspec run -n

